version: "3.7"

services:
  php:
    build:
      context: ./services/php
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './services/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './services/volumes/mysql:/var/lib/mysql'